name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install Cask
      run: git clone https://github.com/cask/cask ~/.cask

    - name: Add to path
      run: echo "${HOME}/.cask/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cask

    - name: Run tests
      run: './run-tests.sh'
